#ifndef OOSERVER_VERSION_H_INCLUDED_
#define OOSERVER_VERSION_H_INCLUDED_

//////////////////////////////////////////////
// Version defines

#define OOSERVER_MAJOR_VERSION  0
#define OOSERVER_MINOR_VERSION  3
#define OOSERVER_BUILD_VERSION  3

#define OOSERVER_VERSION_II(a,b,c)	#a "." #b "." #c
#define OOSERVER_VERSION_I(a,b,c)	OOSERVER_VERSION_II(a,b,c)
#define OOSERVER_VERSION			OOSERVER_VERSION_I(OOSERVER_MAJOR_VERSION,OOSERVER_MINOR_VERSION,OOSERVER_BUILD_VERSION)


#endif // OOSERVER_VERSION_H_INCLUDED_
