#///////////////////////////////////////////////////////////////////////////////////
#//
#// Copyright (C) 2008 Jamal M. Natour
#//
#// This file is part of the OmegaOnline  package.
#//
#// It is free software: you can redistribute it and/or modify
#// it under the terms of the GNU Lesser General Public License as published by
#// the Free Software Foundation, either version 3 of the License, or
#// (at your option) any later version.
#//
#//  is distributed in the hope that it will be useful,
#// but WITHOUT ANY WARRANTY; without even the implied warranty of
#// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#// GNU Lesser General Public License for more details.
#//
#// You should have received a copy of the GNU Lesser General Public License
#// along with this file.  If not, see <http://www.gnu.org/licenses/>.
#//
#///////////////////////////////////////////////////////////////////////////////////
SHELL		:= /bin/sh
PATH		:= /bin:/usr/bin:/sbin:/usr/sbin

# stuff to autoconf
include $(TOP_SRC_DIR)/build/configured_vars.mk
#CC		:= gcc
#CXX		:= g++
#MKDIR		:= mkdir -p
#SED		:= sed -e
#INSTALL	:= install -m

ECHO		:= echo -e
AS		:= as
LD		:= ld
RM		:= rm -f
RMDIR		:= rmdir -v
PWD		:= pwd
DATE		:= date
TOUCH		:= touch

INSTALL_PERM 	:= 755 # rwxr-xr-x
BUILD_DATE	 = $(shell $(DATE) +'%Y%m%d_%I-%M-%S')

#--------------------------------------------
# CAN BE OVERRIDEN ON CMDLINE
#--------------------------------------------
LD_LIBRARY_PATH  = $(BUILD_DIR):$(INSTALL_LIB_ROOT)  # will get expanded at point of use
INSTALL_ROOT     = /usr/local
INSTALL_HDR_DIR = $(INSTALL_ROOT)/include
CMD_LINE_DEFS   := -DVERSION="\"$(BUILD_DATE)\""
#--------------------------------------------

#--------------------------------------------
# Use these directories
#--------------------------------------------
BUILD_ROOT	 = $(TOP_SRC_DIR)
BUILD_DIR 	:= $(BUILD_ROOT)/build
LIB_DIR		:= $(BUILD_DIR)/lib
SRC_DIR 	:= $(BUILD_ROOT)/src
INCLUDE_DIR	:= $(BUILD_ROOT)/include
TEST_DIR	:= $(BUILD_ROOT)/test
#--------------------------------------------

#--------------------------------------------
# Use these headers
#--------------------------------------------
INCLUDES 	:= -I$(SRC_DIR) -I$(INCLUDE_DIR)
#--------------------------------------------

# dependencies and logs live here
#--------------------------------------------
DEPS 		:= "Depend._$(shell basename $(shell $(PWD)) | $(SED) 's:/:_:g')"
BUILD_LOG	:= "Build_$(shell basename $(shell $(PWD)) | $(SED) 's:/:_:g').log"

# fix the order of linking error caused by building two apps from shared c++ sources
# without correctly detecting which files need remaking, 
# This behaviour doesn't manifest with C libaries, so at a guess, this has something 
# to do with template expansion producing a different object file, but don't know.

# Build each target in it's own directory
TARGET_DIR       = "$(shell $(ECHO) $(TARGET) | $(SED) 's:\.:_:g')"
#--------------------------------------------

# allow parallel builds of debug/release source trees
#--------------------------------------------
ifndef RELEASE
BUILD_TYPE	:= Debug
CFLAGS 		:= -g -O0 -DENABLE_DEBUG $(CFLAGS)
CPPFLAGS 	:= -g -O0 -DENABLE_DEBUG $(CPPFLAGS)
BUILD_DIR 	:= $(BUILD_DIR)/Debug
OBJ_DIR 	 = $(BUILD_DIR)/objs_debug/$(TARGET_DIR)
DEPS		:= $(BUILD_DIR)/$(DEPS)_debug
BUILD_LOG	:= $(BUILD_DIR)/$(BUILD_LOG)_debug
else
BUILD_TYPE	:= Release
CFLAGS 		:= -O2 $(CFLAGS)
CPPFLAGS 	:= -O2 $(CPPFLAGS)
OBJ_DIR 	:= $(BUILD_DIR)/objs_release/$(TARGET_DIR)
DEPS		:= $(BUILD_DIR)/$(DEPS)_release
BUILD_LOG	:= $(BUILD_DIR)/$(BUILD_LOG)_release
endif
#--------------------------------------------

#--------------------------------------------
# Build with these flags, only add common libs here
#--------------------------------------------
ANSI_C_89	:= -ansi -std=c89 -pedantic
ANSI_C_99	:= -ansi -std=c99 -pedantic
POSIX_BUILD	:=  -D_XOPEN_SOURCE=500 -D_GNU_SOURCE  -D_BSD_SOURCE
POSIX_C		:= -std=gnu99 -pedantic $(POSIX_BUILD)
WARNINGS	:= -Wall
CFLAGS		:= $(POSIX_C) $(WARNINGS) $(INCLUDES) $(CMD_LINE_DEFS)
CPPFLAGS 	:= -Wall -pthread -fno-rtti -fvisibility=hidden $(INCLUDES) $(CMD_LINE_DEFS) $(POSIX_BUILD)
CXXFLAGS 	:= $(CPPFLAGS)
TEST_CFLAGS	:= $(CFLAGS)
TEST_CPPFLAGS	:= $(CPPFLAGS)
#--------------------------------------------


#handy defaults
ALL_C_SRCS	  = $(wildcard $(SRC_DIR)/*.c)
ALL_CPP_SRCS	  = $(wildcard $(SRC_DIR)/*.cpp)
ALL_TEST_C_SRCS   = $(wildcard $(TEST_DIR)/*.c)
ALL_TEST_CPP_SRCS = $(wildcard $(TEST_DIR)/*.cpp)
ALL_HEADERS	  = $(wildcard $(SRC_DIR)/*.h)
ALL_TEST_HEADERS  = $(wildcard $(TEST_DIR)/*.h)
