
// -*- C++ -*-
// OONet_export.h,v 0.1 2005/07/11 14:25:31 rtaylor
// Definition for Win32 Export directives.
// This file is generated by hand
// ------------------------------
#ifndef OONET_EXPORT_H
#define OONET_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (OONET_HAS_DLL)
#  define OONET_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && OONET_HAS_DLL */

#if !defined (OONET_HAS_DLL)
#  define OONET_HAS_DLL 1
#endif /* ! OONET_HAS_DLL */

#if defined (OONET_HAS_DLL) && (OONET_HAS_DLL == 1)
#  if defined (OONET_BUILD_DLL)
#    define OONet_Export ACE_Proper_Export_Flag
#    define OONET_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define OONET_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* OONET_BUILD_DLL */
#    define OONet_Export ACE_Proper_Import_Flag
#    define OONET_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define OONET_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* OONET_BUILD_DLL */
#else /* OONET_HAS_DLL == 1 */
#  define OONet_Export
#  define OONET_SINGLETON_DECLARATION(T)
#  define OONET_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* OONET_HAS_DLL == 1 */

// Set OONET_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (OONET_NTRACE)
#  if (ACE_NTRACE == 1)
#    define OONET_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define OONET_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !OONET_NTRACE */

#if (OONET_NTRACE == 1)
#  define OONET_TRACE(X)
#else /* (OONET_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define OONET_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (OONET_NTRACE == 1) */

#endif /* OONET_EXPORT_H */

// End of auto generated file.
