
// -*- C++ -*-
// OOCore_export.h,v 0.1 2005/07/11 14:25:31 rtaylor
// Definition for Win32 Export directives.
// This file is generated by hand
// ------------------------------
#ifndef OOCORE_EXPORT_H
#define OOCORE_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (OOCORE_HAS_DLL)
#  define OOCORE_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && OOCORE_HAS_DLL */

#if !defined (OOCORE_HAS_DLL)
#  define OOCORE_HAS_DLL 1
#endif /* ! OOCORE_HAS_DLL */

#if defined (OOCORE_HAS_DLL) && (OOCORE_HAS_DLL == 1)
#  if defined (OOCORE_BUILD_DLL)
#    define OOCore_Export ACE_Proper_Export_Flag
#    define OOCORE_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define OOCORE_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* OOCORE_BUILD_DLL */
#    define OOCore_Export ACE_Proper_Import_Flag
#    define OOCORE_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define OOCORE_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* OOCORE_BUILD_DLL */
#else /* OOCORE_HAS_DLL == 1 */
#  define OOCore_Export
#  define OOCORE_SINGLETON_DECLARATION(T)
#  define OOCORE_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* OOCORE_HAS_DLL == 1 */

// Set OOCORE_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (OOCORE_NTRACE)
#  if (ACE_NTRACE == 1)
#    define OOCORE_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define OOCORE_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !OOCORE_NTRACE */

#if (OOCORE_NTRACE == 1)
#  define OOCORE_TRACE(X)
#else /* (OOCORE_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define OOCORE_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (OOCORE_NTRACE == 1) */

#endif /* OOCORE_EXPORT_H */

// End of auto generated file.
