
// -*- C++ -*-
// OOps_export.h,v 0.1 2005/07/11 14:25:31 rtaylor
// Definition for Win32 Export directives.
// This file is generated by hand
// ------------------------------
#ifndef OOPS_EXPORT_H
#define OOPS_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (OOPS_HAS_DLL)
#  define OOPS_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && OOPS_HAS_DLL */

#if !defined (OOPS_HAS_DLL)
#  define OOPS_HAS_DLL 1
#endif /* ! OOPS_HAS_DLL */

#if defined (OOPS_HAS_DLL) && (OOPS_HAS_DLL == 1)
#  if defined (OOPS_BUILD_DLL)
#    define OOps_Export ACE_Proper_Export_Flag
#    define OOPS_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define OOPS_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* OOPS_BUILD_DLL */
#    define OOps_Export ACE_Proper_Import_Flag
#    define OOPS_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define OOPS_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* OOPS_BUILD_DLL */
#else /* OOPS_HAS_DLL == 1 */
#  define OOps_Export
#  define OOPS_SINGLETON_DECLARATION(T)
#  define OOPS_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* OOPS_HAS_DLL == 1 */

// Set OOPS_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (OOPS_NTRACE)
#  if (ACE_NTRACE == 1)
#    define OOPS_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define OOPS_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !OOPS_NTRACE */

#if (OOPS_NTRACE == 1)
#  define OOPS_TRACE(X)
#else /* (OOPS_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define OOPS_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (OOPS_NTRACE == 1) */

#endif /* OOPS_EXPORT_H */

// End of auto generated file.
