#///////////////////////////////////////////////////////////////////////////////////
#//
#// Copyright (C) 2008 Jamal M. Natour
#//
#// This file is part of the OmegaOnline  package.
#//
#//  is free software: you can redistribute it and/or modify
#// it under the terms of the GNU Lesser General Public License as published by
#// the Free Software Foundation, either version 3 of the License, or
#// (at your option) any later version.
#//
#//  is distributed in the hope that it will be useful,
#// but WITHOUT ANY WARRANTY; without even the implied warranty of
#// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#// GNU Lesser General Public License for more details.
#//
#// You should have received a copy of the GNU Lesser General Public License
#// along with this file.  If not, see <http://www.gnu.org/licenses/>.
#//
#///////////////////////////////////////////////////////////////////////////////////
# Boilerplate for Omega applications
SHELL		:= /bin/sh
BUILD_ROOT 	:= bin
ECHO		:= echo -e
RM		:= rm -f
CC 		:= g++
INSTALL		:= install -m
INSTALL_PERM 	:= 755 # rwxr-xr-x


INCLUDES 	:= -I include/ -I include/OOCore -I include/OTL# search for headers here
# build with these flags, only add common libs here
CPPFLAGS 	:= -Wall -fno-rtti -Wno-non-virtual-dtor -pthread -fvisibility=hidden $(INCLUDES)
CXXFLAGS 	:= $(CPPFLAGS)

# dependencies live here
DEPS 		:= ".depend"

# allow parallel builds of debug/release source trees
ifndef RELEASE
BUILD_TYPE	:= Debug
DEPS		:= $(DEPS)_debug
OBJ_DIR 	:= $(SRC_DIR)/objs_debug
CPPFLAGS 	:= -g -O0 -DOMEGA_DEBUG $(CPPFLAGS)
BUILD_DIR 	:= $(BUILD_ROOT)/Debug
else
BUILD_TYPE	:= Release
OBJ_DIR 	:= $(SRC_DIR)/objs_release
DEPS		:= $(DEPS)_release
BUILD_DIR 	:= $(BUILD_ROOT)
CPPFLAGS 	:= -O2 $(CPPFLAGS)
endif


