// -*- C++ -*- generated by wxGlade 0.4.1 on Thu May 18 07:29:30 2006

#include <wx/wx.h>
#include <wx/image.h>
#include "./wxGladeAssist.h"

#ifndef ABOUTDLG_H
#define ABOUTDLG_H

// begin wxGlade: ::dependencies
#include <wx/statline.h>
// end wxGlade


class AboutDlg: public wxDialog {
public:
    // begin wxGlade: AboutDlg::ids
    // end wxGlade

    AboutDlg(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: AboutDlg::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: AboutDlg::attributes
    wxStaticBitmap* m_picIcon;
    wxStaticText* m_lblDesc;
    wxStaticLine* m_line;
    wxStaticText* m_lblVersion;
    wxStdButtons* m_buttons;
    // end wxGlade
}; // wxGlade: end class


#endif // ABOUTDLG_H
