// -*- C++ -*- generated by wxGlade 0.4.1 on Fri May 19 12:16:37 2006

#include <wx/wx.h>
#include <wx/image.h>
#include "./wxGladeAssist.h"

#ifndef ADDFAVDLG_H
#define ADDFAVDLG_H

// begin wxGlade: ::dependencies
// end wxGlade


class AddFavDlg: public wxDialog {
public:
    // begin wxGlade: AddFavDlg::ids
    // end wxGlade
	enum
	{
		ID_NAME = 1
	};

    AddFavDlg(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

	wxString	m_strName;

private:
    // begin wxGlade: AddFavDlg::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: AddFavDlg::attributes
    wxStaticText* m_lblName;
    wxTextCtrl* m_txtName;
    wxStdButtons* m_buttons;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    void OnTextChanged(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // ADDFAVDLG_H
