// -*- C++ -*- generated by wxGlade 0.4.1 on Thu May 18 07:29:30 2006

#include <wx/wx.h>
#include <wx/image.h>
#include "wxGladeAssist.h"

#ifndef EDITUINTDLG_H
#define EDITUINTDLG_H

// begin wxGlade: ::dependencies
// end wxGlade


class EditUIntDlg: public wxDialog {
public:
    // begin wxGlade: EditUIntDlg::ids
    // end wxGlade
	enum 
	{
		ID_BASE = 1
	};

    EditUIntDlg(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

	wxString	m_strName;
	wxString	m_strValue;
	int			m_nBase;

private:
    // begin wxGlade: EditUIntDlg::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: EditUIntDlg::attributes
    wxStaticText* m_lblName;
    wxTextCtrl* m_txtName;
    wxStaticText* m_lblValue;
    wxTextCtrl* m_txtValue;
    wxRadioBox* m_rbxBase;
    wxStdButtons* m_buttons;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    void OnBaseChanged(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // EDITUINTDLG_H
