// -*- C++ -*- generated by wxGlade 0.4.1 on Thu May 18 08:34:03 2006

#include <wx/wx.h>
#include <wx/image.h>
#include "wxGladeAssist.h"

#ifndef EDITSTRINGDLG_H
#define EDITSTRINGDLG_H

// begin wxGlade: ::dependencies
// end wxGlade


class EditStringDlg: public wxDialog {
public:
    // begin wxGlade: EditStringDlg::ids
    // end wxGlade

    EditStringDlg(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

	wxString	m_strName;
	wxString	m_strValue;

private:
    // begin wxGlade: EditStringDlg::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: EditStringDlg::attributes
    wxStaticText* m_lblName;
    wxTextCtrl* m_txtName;
    wxStaticText* m_lblValue;
    wxTextCtrl* m_txtValue;
    wxStdButtons* m_buttons;
    // end wxGlade
}; // wxGlade: end class


#endif // EDITSTRINGDLG_H
