// -*- C++ -*- generated by wxGlade 0.6.3 on Mon Mar 10 14:32:36 2008

#include "stdafx.h"
#include "EditValueDescDlg.h"

// begin wxGlade: ::extracode

// end wxGlade

EditValueDescDlg::EditValueDescDlg(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long /*style*/):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE)
{
    // begin wxGlade: EditValueDescDlg::EditValueDescDlg
    m_lblName = new wxStaticText(this, wxID_ANY, wxT("Key &Name:"));
    m_txtName = new wxTextCtrl(this, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxTE_READONLY);
	m_lblValue = new wxStaticText(this, wxID_ANY, wxT("&Value Name:"));
    m_txtValue = new wxTextCtrl(this, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxTE_READONLY);
    m_lblDesc = new wxStaticText(this, wxID_ANY, wxT("&Description:"));
    m_txtDesc = new wxTextCtrl(this, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE);
    m_buttons = new wxStdButtons(this, wxID_ANY, wxOK|wxCANCEL);

    set_properties();
    do_layout();
    // end wxGlade

	m_txtDesc->SetValidator(wxGenericValidator(&m_strDesc));
	m_txtValue->SetValidator(wxGenericValidator(&m_strValue));
	m_txtName->SetValidator(wxGenericValidator(&m_strName));
}

void EditValueDescDlg::set_properties()
{
    // begin wxGlade: EditValueDescDlg::set_properties
    SetTitle(wxT("Edit Value Description"));
	m_txtDesc->SetMinSize(wxDLG_UNIT(m_txtDesc, wxSize(350, 14*8)));
    // end wxGlade
}

void EditValueDescDlg::do_layout()
{
    // begin wxGlade: EditValueDescDlg::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    sizer_1->Add(m_lblName, 0, wxLEFT|wxRIGHT|wxTOP, 7);
    sizer_1->Add(m_txtName, 0, wxALL|wxEXPAND, 7);
	sizer_1->Add(m_lblValue, 0, wxLEFT|wxRIGHT|wxTOP, 7);
    sizer_1->Add(m_txtValue, 0, wxALL|wxEXPAND, 7);
    sizer_1->Add(m_lblDesc, 0, wxLEFT|wxRIGHT|wxTOP, 7);
    sizer_1->Add(m_txtDesc, 1, wxALL|wxEXPAND, 7);
    sizer_1->Add(m_buttons, 0, wxALL|wxEXPAND, 7);
    SetSizer(sizer_1);
    sizer_1->Fit(this);
    Layout();
    // end wxGlade
}
