// -*- C++ -*- generated by wxGlade 0.6.3 on Mon Mar 10 14:32:36 2008

#include <wx/wx.h>
#include <wx/image.h>
#include "wxGladeAssist.h"

#ifndef EDITKEYDESC_H
#define EDITKEYDESC_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade


class EditKeyDescDlg: public wxDialog {
public:
    // begin wxGlade: EditKeyDescDlg::ids
    // end wxGlade

    EditKeyDescDlg(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

	wxString	m_strName;
	wxString	m_strDesc;

private:
    // begin wxGlade: EditKeyDescDlg::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: EditKeyDescDlg::attributes
    wxStaticText* m_lblName;
    wxTextCtrl* m_txtName;
    wxStaticText* m_lblDesc;
    wxTextCtrl* m_txtDesc;
    wxStdButtons* m_buttons;
    // end wxGlade
}; // wxGlade: end class


#endif // EDITKEYDESC_H
