// -*- C++ -*- generated by wxGlade 0.6.3 on Mon Mar 10 14:32:36 2008

#include "stdafx.h"
#include "./EditKeyDescDlg.h"

// begin wxGlade: ::extracode

// end wxGlade

EditKeyDescDlg::EditKeyDescDlg(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE)
{
    // begin wxGlade: EditKeyDescDlg::EditKeyDescDlg
    m_lblName = new wxStaticText(this, wxID_ANY, wxT("Key &Name:"));
    m_txtName = new wxTextCtrl(this, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxTE_READONLY);
    m_lblDesc = new wxStaticText(this, wxID_ANY, wxT("&Description:"));
    m_txtDesc = new wxTextCtrl(this, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE);
    m_buttons = new wxStdButtons(this, wxID_ANY, wxOK|wxCANCEL);

    set_properties();
    do_layout();
    // end wxGlade

	m_txtDesc->SetValidator(wxGenericValidator(&m_strDesc));
	m_txtName->SetValidator(wxGenericValidator(&m_strName));
}

void EditKeyDescDlg::set_properties()
{
    // begin wxGlade: EditKeyDescDlg::set_properties
    SetTitle(wxT("Edit Key Description"));
	m_txtDesc->SetMinSize(wxDLG_UNIT(m_txtDesc, wxSize(350, 14*8)));
    // end wxGlade
}

void EditKeyDescDlg::do_layout()
{
    // begin wxGlade: EditKeyDescDlg::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    sizer_1->Add(m_lblName, 0, wxLEFT|wxRIGHT|wxTOP, 7);
    sizer_1->Add(m_txtName, 0, wxALL|wxEXPAND, 7);
    sizer_1->Add(m_lblDesc, 0, wxLEFT|wxRIGHT|wxTOP, 7);
    sizer_1->Add(m_txtDesc, 1, wxALL|wxEXPAND, 7);
    sizer_1->Add(m_buttons, 0, wxALL|wxEXPAND, 7);
    SetSizer(sizer_1);
    sizer_1->Fit(this);
    Layout();
    // end wxGlade
}
