// -*- C++ -*- generated by wxGlade 0.6.3 on Mon Mar 10 14:32:36 2008

#include <wx/wx.h>
#include <wx/image.h>
#include "./wxGladeAssist.h"

#ifndef EDITVALUEDESC_H
#define EDITVALUEDESC_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade


class EditValueDescDlg: public wxDialog {
public:
    // begin wxGlade: EditValueDescDlg::ids
    // end wxGlade

    EditValueDescDlg(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

	wxString	m_strName;
	wxString	m_strValue;
	wxString	m_strDesc;

private:
    // begin wxGlade: EditValueDescDlg::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: EditValueDescDlg::attributes
    wxStaticText* m_lblName;
    wxTextCtrl* m_txtName;
	wxStaticText* m_lblValue;
    wxTextCtrl* m_txtValue;
    wxStaticText* m_lblDesc;
    wxTextCtrl* m_txtDesc;
    wxStdButtons* m_buttons;
    // end wxGlade
}; // wxGlade: end class


#endif // EDITVALUEDESC_H
