// -*- C++ -*- generated by wxGlade 0.4.1 on Thu May 18 09:30:38 2006

#include <wx/wx.h>
#include <wx/image.h>

#ifndef FINDDLG_H
#define FINDDLG_H

// begin wxGlade: ::dependencies
// end wxGlade


class FindDlg: public wxDialog {
public:
    // begin wxGlade: FindDlg::ids
    // end wxGlade

	enum
	{
		ID_FIND = 1
	};

    FindDlg(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

	wxString	m_strFind;
	bool		m_bKeys;
	bool		m_bValues;
	bool		m_bData;
	bool		m_bMatchAll;
	bool		m_bIgnoreCase;

private:
    // begin wxGlade: FindDlg::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: FindDlg::attributes
    wxStaticBox* m_sizer_4_staticbox;
    wxStaticText* m_lblFindWhat;
    wxTextCtrl* m_txtFind;
    wxCheckBox* m_chkKeys;
    wxCheckBox* m_chkValues;
    wxCheckBox* m_chkData;
    wxCheckBox* m_chkMatchAll;
    wxCheckBox* m_chkIgnoreCase;
    wxButton* m_btnFind;
    wxButton* m_btnCancel;
    // end wxGlade
    void OnTextChanged(wxCommandEvent &event); // wxGlade: <event_handler>

protected:
    DECLARE_EVENT_TABLE()
}; // wxGlade: end class


#endif // FINDDLG_H
