// -*- C++ -*- generated by wxGlade 0.4.1 on Fri May 19 12:33:00 2006

#include "stdafx.h"
#include "./RemoveFavDlg.h"


RemoveFavDlg::RemoveFavDlg(wxWindow* parent, wxFileHistory* pHistory, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, -1, wxT(""), pos, size, wxDEFAULT_DIALOG_STYLE)
{
    // begin wxGlade: RemoveFavDlg::RemoveFavDlg
    m_lblSelect = new wxStaticText(this, -1, _("Select Favourite(s):"));
    const wxString m_lstFavs_choices[] = {
        _("Shutup!")
    };
    m_lstFavs = new wxListBox(this, ID_LIST, wxDefaultPosition, wxDefaultSize, 1, m_lstFavs_choices, wxLB_MULTIPLE|wxLB_NEEDED_SB);
    m_buttons = new wxStdButtons(this, -1, wxOK|wxCANCEL);

    set_properties();
    do_layout();
    // end wxGlade

	m_lstFavs->Clear();

	wxArrayString arrStr;
	for (size_t i=0;i<pHistory->GetCount();++i)
	{
		arrStr.Add(pHistory->GetHistoryFile(i));
	}
	m_lstFavs->InsertItems(arrStr,0);

	m_lstFavs->SetValidator(wxGenericValidator(&m_selections));

	wxWindow* pOK = FindWindow(wxID_OK);
	if (pOK)
		pOK->Enable(false);	
}

BEGIN_EVENT_TABLE(RemoveFavDlg, wxDialog)
    // begin wxGlade: RemoveFavDlg::event_table
    EVT_LISTBOX(ID_LIST, RemoveFavDlg::OnListSelChanged)
    // end wxGlade
END_EVENT_TABLE();


void RemoveFavDlg::OnListSelChanged(wxCommandEvent &event)
{
    wxWindow* pOK = FindWindow(wxID_OK);
	if (pOK)
	{
		wxArrayInt sels;
		pOK->Enable(m_lstFavs->GetSelections(sels)>0);	
	}
}


// wxGlade: add RemoveFavDlg event handlers


void RemoveFavDlg::set_properties()
{
    // begin wxGlade: RemoveFavDlg::set_properties
    SetTitle(_("Remove Favourites"));
    m_lstFavs->SetMinSize(wxDLG_UNIT(m_lstFavs, wxSize(200, 59)));
    m_lstFavs->SetSelection(-1);
    // end wxGlade
}


void RemoveFavDlg::do_layout()
{
    // begin wxGlade: RemoveFavDlg::do_layout
    wxBoxSizer* m_sizer_1 = new wxBoxSizer(wxVERTICAL);
    m_sizer_1->Add(m_lblSelect, 0, wxLEFT|wxRIGHT|wxTOP, 7);
    m_sizer_1->Add(m_lstFavs, 0, wxALL|wxADJUST_MINSIZE, 7);
    m_sizer_1->Add(m_buttons, 0, wxALL|wxEXPAND, 7);
    SetAutoLayout(true);
    SetSizer(m_sizer_1);
    m_sizer_1->Fit(this);
    m_sizer_1->SetSizeHints(this);
    Layout();
    // end wxGlade
}

