// -*- C++ -*- generated by wxGlade 0.4.1 on Fri May 19 12:33:00 2006

#include <wx/wx.h>
#include <wx/image.h>
#include "wxGladeAssist.h"

#ifndef REMOVEFAVDLG_H
#define REMOVEFAVDLG_H

// begin wxGlade: ::dependencies
// end wxGlade


class RemoveFavDlg: public wxDialog {
public:
    // begin wxGlade: RemoveFavDlg::ids
    // end wxGlade
	enum
	{
		ID_LIST = 1
	};

    RemoveFavDlg(wxWindow* parent, wxFileHistory* pHistory, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

	wxArrayInt	m_selections;
	
private:
    // begin wxGlade: RemoveFavDlg::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: RemoveFavDlg::attributes
    wxStaticText* m_lblSelect;
    wxListBox* m_lstFavs;
    wxStdButtons* m_buttons;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    void OnListSelChanged(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // REMOVEFAVDLG_H
